import { randomBytes } from 'crypto';
import { config } from '../config.js';
import type { RemoteRun } from '../queue/types.js';

// Text Vigil writes to the persistent shell, and parsers for what it echoes back.
// No I/O here.

// POSIX single-quote escaping.
export function sq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

// Base directory for run dirs, as a double-quoted shell word ($HOME etc. still expand).
export function remoteBaseWord(): string {
  return `"${config.remoteDir.replace(/["`\\]/g, '\\$&')}"`;
}

export const FALLBACK_BASE_WORD = '"${TMPDIR:-/tmp}/vigil-runs"';

// Run dir names are generated by Vigil — refuse anything else before touching files.
const RUN_NAME_RE = /^[A-Za-z0-9_-]+$/;

export function isRunName(name: string): boolean {
  return RUN_NAME_RE.test(name);
}

export function runDirName(dir: string): string {
  return dir.split('/').pop() ?? '';
}

export function isRunDir(dir: string): boolean {
  return dir.startsWith('/') && isRunName(runDirName(dir));
}

export function makeSentinel(): string {
  return `VIGIL_${randomBytes(8).toString('hex')}`;
}

// ─── Handshake ────────────────────────────────────────────────────────────────

// No stty needed (no PTY). Disable tracing, make SIGINT harmless to the idle
// shell (a Stop can race a command finishing), and report the shell pid — the
// root of the process tree we signal when stopping commands.
export const HANDSHAKE_LINE = 'set +xv 2>/dev/null; trap : INT; echo "VIGIL_READY:$$"\n';

export function parseHandshake(buf: string): number | null {
  const match = buf.match(/VIGIL_READY:(\d+)\r?\n/);
  return match ? parseInt(match[1], 10) : null;
}

// ─── Run wrapper ──────────────────────────────────────────────────────────────
//
// Phase 1 creates the run dir (stdin FIFO, output log, pid files) and reports it
// with a START marker (or NOTRACK). Phase 2 — the command itself — is written
// once that marker comes back, and ends with an END marker.

// The FIFO holder is started from a subshell so it is not one of the shell's
// jobs (no "Killed" job notices in the output), with stdio off the channel.
export function prepareRunLine(name: string, sentinel: string): string {
  return (
    `__vd=; for __vb in ${remoteBaseWord()} ${FALLBACK_BASE_WORD}; do ` +
      `if (umask 077; mkdir -p "$__vb/${name}" && mkfifo "$__vb/${name}/in" && : > "$__vb/${name}/out") 2>/dev/null; ` +
      `then __vd="$__vb/${name}"; break; fi; done; ` +
    `if [ -n "$__vd" ]; then ` +
      `( sleep 2147483647 > "$__vd/in" < /dev/null 2>/dev/null & echo $! > "$__vd/holder" ); __vh=$(cat "$__vd/holder"); ` +
      `echo "$$" > "$__vd/shell"; date -u +%Y-%m-%dT%H:%M:%SZ > "$__vd/started"; ` +
      `echo "${sentinel}:START:$__vh:$$:$__vd"; ` +
    `else echo "${sentinel}:NOTRACK"; fi\n`
  );
}

export type RunStart =
  | { tracked: true;  remote: RemoteRun; rest: string }
  | { tracked: false; rest: string };

export function parseRunStart(buf: string, sentinel: string): RunStart | null {
  const start = buf.match(new RegExp(`${sentinel}:START:(\\d+):(\\d+):([^\\r\\n]*)\\r?\\n`));
  if (start) {
    return {
      tracked: true,
      remote: {
        dir:        start[3],
        holder_pid: parseInt(start[1], 10),
        shell_pid:  parseInt(start[2], 10),
        started_at: new Date().toISOString(),
      },
      rest: buf.slice(start.index! + start[0].length),
    };
  }

  const noTrack = buf.match(new RegExp(`${sentinel}:NOTRACK\\r?\\n`));
  if (noTrack) return { tracked: false, rest: buf.slice(noTrack.index! + noTrack[0].length) };
  return null;
}

// Everything after `}` must stay on one line: the shell parses the whole line
// before running it, so the post-steps run even if our channel has gone away by
// the time the command exits. The holder is SIGKILLed: it inherits ignored
// signals from the shell (e.g. `trap '' TERM`).
export function trackedCommandLine(command: string, sentinel: string): string {
  return (
    `${wrapFunction(command)} < "$__vd/in" > "$__vd/out" 2>&1; __ve=$?; trap : INT; ` +
    `echo "$__ve" > "$__vd/exit"; kill -9 "$__vh" 2>/dev/null; echo "${sentinel}:END:$__ve:$(wc -c < "$__vd/out")"\n`
  );
}

// Fallback when no run dir could be created: output comes back over the channel.
export function untrackedCommandLine(command: string, sentinel: string): string {
  return `${wrapFunction(command)} 2>&1; __ve=$?; trap : INT; echo "${sentinel}:END:$__ve:0"\n`;
}

export function parseRunEnd(buf: string, sentinel: string): { exitCode: number; index: number } | null {
  const end = buf.match(new RegExp(`${sentinel}:END:(\\d+):\\s*(\\d+)\\r?\\n`));
  return end ? { exitCode: parseInt(end[1], 10), index: end.index! } : null;
}

// Untracked output is held back by this much so a split sentinel is never emitted.
export function sentinelHoldback(sentinel: string): number {
  return sentinel.length + 32;
}

// Run the command as a shell function so state (cd, export) still persists, with
// a SIGINT trap that returns from it: Stop can then abort loops and builtins
// running in the shell itself without killing the shell. The newline before `}`
// lets commands end in a comment or heredoc. Callers append redirections and
// restore `trap : INT` straight after.
function wrapFunction(command: string): string {
  return `__vigil_run() { ${command}\n}; trap 'return 130' INT; __vigil_run`;
}
